### PR TITLE
Change default "playing Silence" to not playing anything, etc

### PR DESCRIPTION
**Pull request by compujosh**
-Change default "playing Silence" to not playing anything  
**-Adds a compiled windows binary (.exe)**  
-Add sample bat file  
--Fill in details, rename to "run.bat" and double click to run  
-Update README.md  
--Remove broken image  
--Update default for -g

### CODE REVIEW

**Comment by jonas747** [comment]
I don't wanna include a compiled binary in the repo, I think i'm gonna make a release instead (with binaries for linux and windows), if you remove that then the rest looks good.

**Comment by compujosh** [comment]
Alright, that sounds good. I'll remove it when I get a chance

**Comment by compujosh** [comment]
In case you weren't notified: the binary is removed

**Comment by jonas747** [comment]
thanks, sorry for being a bit slow

**Pull request merged**
